#Modifique el archivo .template que es el que genera los de configuracion con el script /home/hvidal/.config/hypr/scripts/theme.sh
cursor_shape          Underline
cursor_underline_thickness 1
window_padding_width  20

# Special
#background #1E1F27
background #16141a
foreground #8b8792

tab_bar_style powerline

active_tab_background #8b8792
active_tab_foreground #29262e
inactive_tab_background #29262e
inactive_tab_foreground #8b8792

active_border_color     #5f6a9c
inactive_border_color   #7D7D7D

# Black
color0 #585260
color8 #595361

# Red
color1 #924f58
color9 #b56670

# Green
color2  #5d8686
color10 #73a0a0

# Yellow
color3  #a08061
color11 #c19a78

# Blue 
color4  #5f7e94
color12 #789bb3

# Magenta
color5  #685286
color13 #896ca8

# Cyan
color6  #5f6a9c
color14 #7985b8

# White
color7  #c2bfc7
color15 #e2dfe7

# Cursor
cursor #8b8792
cursor_text_color #1a1b26

# Selection highlight
selection_foreground #7aa2f7
selection_background #28344a
